# Generated by Django 4.2.2 on 2023-10-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, verbose_name=11)),
                ('Name', models.CharField(max_length=255)),
                ('no_of_guests', models.IntegerField(verbose_name=6)),
                ('bookingdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=5)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
